"""adding rating column in Posts table

Revision ID: 2cfb506bcd17
Revises: b2e88c3daace
Create Date: 2024-02-21 21:59:29.697439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfb506bcd17'
down_revision: Union[str, None] = 'b2e88c3daace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'rating')
    # ### end Alembic commands ###
